### ISSUE TITLE
Malloc Error when drawing scene

### ISSUE THREAD

**Issue by syleck** [psiwerks/veng#10]
GDB Backtrace
```
0x00007ffff728aef5 in raise () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff728aef5 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7274862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff72ccf38 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff72d4bea in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff72d98dc in malloc () from /usr/lib/libc.so.6
#5  0x00007ffff60282a2 in ?? () from /usr/lib/dri/i965_dri.so
#6  0x00007ffff63b6d2d in ?? () from /usr/lib/dri/i965_dri.so
#7  0x00007ffff63202db in ?? () from /usr/lib/dri/i965_dri.so
#8  0x00007ffff6325e10 in ?? () from /usr/lib/dri/i965_dri.so
#9  0x00007ffff632b38a in ?? () from /usr/lib/dri/i965_dri.so
#10 0x00007ffff6325e10 in ?? () from /usr/lib/dri/i965_dri.so
#11 0x00007ffff63293d7 in ?? () from /usr/lib/dri/i965_dri.so
#12 0x00007ffff6325e10 in ?? () from /usr/lib/dri/i965_dri.so
#13 0x00007ffff6328ab2 in ?? () from /usr/lib/dri/i965_dri.so
#14 0x00007ffff6336001 in ?? () from /usr/lib/dri/i965_dri.so
#15 0x00007ffff632c0c4 in ?? () from /usr/lib/dri/i965_dri.so
#16 0x00007ffff6313f42 in ?? () from /usr/lib/dri/i965_dri.so
#17 0x00007ffff6336001 in ?? () from /usr/lib/dri/i965_dri.so
#18 0x00007ffff631fc9d in ?? () from /usr/lib/dri/i965_dri.so
#19 0x00007ffff67c10ff in ?? () from /usr/lib/dri/i965_dri.so
#20 0x00007ffff5f8db9c in ?? () from /usr/lib/dri/i965_dri.so
#21 0x00007ffff62d91ec in ?? () from /usr/lib/dri/i965_dri.so
#22 0x00007ffff61c4cc1 in ?? () from /usr/lib/dri/i965_dri.so
#23 0x00007ffff61c6ce5 in ?? () from /usr/lib/dri/i965_dri.so
#24 0x00007ffff61c73ba in ?? () from /usr/lib/dri/i965_dri.so
#25 0x00007ffff60aae80 in ?? () from /usr/lib/dri/i965_dri.so
#26 0x00007ffff7c06481 in irr::video::COpenGLDriver::beginScene(bool, bool, irr::video::SColor, irr::video::SExposedVideoData const&, irr::core::rect<int>*) () from /usr/lib/libIrrlicht.so.1.8
#27 0x000055555557b9f6 in main (argc=2, argv=0x7fffffffe238) at src/main.cpp:223
```
How

**Comment by anugla** [comment]
This doesnt seem to happen anymore but I dont think its fixed

**Comment by syleck** [comment]
This hasnt happened in a long time so I think its fixed
